### ISSUE TITLE
Not able to get list of users in admin dashboard.

### ISSUE THREAD

**Issue by ashishratre404** [safak/youtube2022#19]
This is the error showing in the console `Failed to load resource: the server responded with a status of 401 (Unauthorized)`.
When I login from postman it is storing a cookie in postman, but when login from UI it is not storing any cookie in the browser and I think this is why I am able to get user data from postman but not from UI.
If you could help me to resolve this issue I would be thankful. `(timestamp in video : 3:09:48)`

**Comment by ashishratre404** [comment]
I have already enabled cookie in the browser but still not working.

**Comment by gonzhilaz** [comment]
is this already solved?

**Comment by ashishratre404** [comment]
> is this already solved?

Yes, Its working now.
